#:kivy 1.7.2

Root:
	BoxLayout:
		orientation: 'vertical'
		BoxLayout:
			orientation: 'horizontal'
			Label:
				top: 5
				text: 'Weird Factor'
			Slider:
				id: slider
				max: 0.5
				value: 0.25
				#on_value: bar.value = self.value
		Button:
			pos_hint: {'center_x':.5, 'center_y': .5}
			size_hint: 0.7, 0.2
			text: "Feed Me"
		Label:
			id: 'ingredients'
			font_size: 50
			rgba: 0.3, 1.0, 0.3, 1.0
			text: 'Ingredients'